apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: jf2k481bx-nodejs 
  janus-idp.io/tekton: jf2k481bx-nodejs
  backstage.io/kubernetes-id: jf2k481bx-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: jf2k481bx-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml