apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jf2k481bx-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jf2k481bx-nodejs 
  name: jf2k481bx-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: jf2k481bx-nodejs 
