apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: jf2k481bx-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:702f9bb464bfeced1c15d45555c4addb2cd22e57@sha256:e27077ea4f31ab2b9c3add4c5d0ea562c0936a2b5bdab36966f3685190e3a1f2
          name: container-image
